# WSO2SHARED_DB Update Queries

# 1. UM_DOMAIN
# Delete existing PRIMARY user domain records
# Replace the UM_DOMAIN_NAME from "TEST" to "PRIMARY"
DELETE FROM UM_DOMAIN WHERE UM_DOMAIN_NAME='PRIMARY';
UPDATE `WSO2SHARED_DB`.`UM_DOMAIN` SET `UM_DOMAIN_NAME`=REPLACE(`UM_DOMAIN_NAME`,'TEST','PRIMARY');


# 2. UM_PERMISSION
# Remove "TEST" prefix from UM_RESOURCE_ID column
UPDATE `WSO2SHARED_DB`.`UM_PERMISSION` SET `UM_RESOURCE_ID`=REPLACE(`UM_RESOURCE_ID`,'TEST/','');


# 3. UM_HYBRID_ROLE
# Remove "TEST" prefix from UM_ROLE_NAME column
UPDATE `WSO2SHARED_DB`.`UM_HYBRID_ROLE` SET `UM_ROLE_NAME`=REPLACE(`UM_ROLE_NAME`,'TEST_','');


# 3. REG_ASSOCIATION
# Remove "TEST" prefix from the REG_SOURCEPATH and REG_TARGETPATH columns
UPDATE `WSO2SHARED_DB`.`REG_ASSOCIATION` SET `REG_SOURCEPATH`=REPLACE(`REG_SOURCEPATH`,'TEST/',''), `REG_TARGETPATH`=REPLACE(`REG_TARGETPATH`,'TEST/','');


# 4. REG_LOG
# Remove "TEST" prefix from the REG_PATH and REG_USER_ID columns
UPDATE `WSO2SHARED_DB`.`REG_LOG` SET `REG_PATH`=REPLACE(`REG_PATH`,'TEST/',''), `REG_USER_ID`=REPLACE(`REG_USER_ID`,'TEST/','');


# 5. REG_RESOURCE
# Delete the row contains REG_PATH_ID of '/_system/governance/apimgt/applicationdata/provider/TEST' from WSO2SHARED_DB.REG_PATH
# Remove "TEST" prefix from REG_CREATOR and REG_LAST_UPDATOR columns
DELETE FROM `WSO2SHARED_DB.REG_RESOURCE` WHERE REG_PATH_ID IN 
			(SELECT REG_PATH_ID 
			FROM `WSO2SHARED_DB.REG_PATH`
            WHERE REG_PATH_VALUE='/_system/governance/apimgt/applicationdata/provider/TEST'
);
UPDATE `WSO2SHARED_DB`.`REG_RESOURCE` SET `REG_CREATOR`=REPLACE(`REG_CREATOR`,'TEST/',''), `REG_LAST_UPDATOR`=REPLACE(`REG_LAST_UPDATOR`,'TEST/','');


# 6. REG_PATH
# Delete the row contains REG_PATH_VALUE of '/_system/governance/apimgt/applicationdata/provider/TEST' from WSO2SHARED_DB.REG_PATH
# Remove "TEST" prefix from REG_PATH_VALUE column
DELETE FROM `WSO2SHARED_DB.REG_PATH` WHERE REG_PATH_VALUE='/_system/governance/apimgt/applicationdata/provider/TEST';
UPDATE `WSO2SHARED_DB`.`REG_PATH` SET `REG_PATH_VALUE`=REPLACE(`REG_PATH_VALUE`,'TEST/','');