# UM_DB Update Queries
----------------------

# 1. UM_DOMAIN
# Delete existing PRIMARY user domain records
# Replace the UM_DOMAIN_NAME from "TEST" to "PRIMARY"
DELETE FROM UM_DOMAIN WHERE UM_DOMAIN_NAME='PRIMARY';
UPDATE `WSO2USER_DB`.`UM_DOMAIN` SET `UM_DOMAIN_NAME`=REPLACE(`UM_DOMAIN_NAME`,'TEST','PRIMARY');

# 2. UM_PERMISSION
# Remove "TEST" prefix from UM_RESOURCE_ID column
UPDATE `WSO2USER_DB`.`UM_PERMISSION` SET `UM_RESOURCE_ID`=REPLACE(`UM_RESOURCE_ID`,'TEST/','');

# 3. UM_HYBRID_ROLE
# Remove "TEST" prefix from UM_ROLE_NAME column
UPDATE `WSO2USER_DB`.`UM_HYBRID_ROLE` SET `UM_ROLE_NAME`=REPLACE(`UM_ROLE_NAME`,'TEST_','');


